CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    login VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE Locations (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    user_id INT REFERENCES Users(id) ON DELETE CASCADE,
    latitude DECIMAL(9,6) NOT NULL,
    longitude DECIMAL(9,6) NOT NULL
);

CREATE TABLE Sessions (
    id UUID DEFAULT RANDOM_UUID() PRIMARY KEY,
    user_id INT REFERENCES Users(id) ON DELETE CASCADE,
    expiresAt TIMESTAMP NOT NULL
);