CREATE TABLE Users (
   id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   login VARCHAR(100) UNIQUE NOT NULL,
   password VARCHAR(255) NOT NULL
);

CREATE TABLE Locations (
   id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   name VARCHAR(255) NOT NULL,
   user_id INT REFERENCES Users(id) ON DELETE CASCADE,
   latitude DECIMAL(9,6) NOT NULL,
   longitude DECIMAL(9,6) NOT NULL
);

CREATE TABLE Sessions (
   id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
   user_id INT REFERENCES Users(id) ON DELETE CASCADE,
   expiresAt TIMESTAMP NOT NULL
);
